# Generated by Django 3.2.4 on 2021-06-07 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(blank=True, choices=[('First Year Student', 'First Year Student'), ('Proffessor', 'Proffessor'), ('Transfare student', 'Transfare student')], max_length=50, null=True),
        ),
    ]
