# Generated by Django 3.2.4 on 2021-06-29 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_college',
            field=models.BooleanField(default=False),
        ),
    ]
