# Generated by Django 3.2.4 on 2021-06-29 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='related_field',
            new_name='college',
        ),
        migrations.RenameField(
            model_name='contactdetail',
            old_name='related_field',
            new_name='college',
        ),
        migrations.AddField(
            model_name='college',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
    ]
