# Generated by Django 3.2.4 on 2021-06-16 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Demographic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('religion', models.CharField(blank=True, choices=[('Christian', 'Christian'), ('Hindu', 'Hindu'), ('Muslim', 'Muslim')], max_length=30, null=True)),
                ('race', models.CharField(blank=True, choices=[('Black', 'Black'), ('White', 'White'), ('Asian', 'Asian')], max_length=30, null=True)),
                ('consent', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(blank=True, max_length=200, null=True)),
                ('date_of_entry', models.DateField()),
                ('school_type', models.BooleanField()),
                ('graduation_status', models.BooleanField()),
                ('graduation_date', models.DateField(blank=True, null=True)),
                ('progression_status', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, max_length=250, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Education',
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_status', models.CharField(blank=True, choices=[('Married', 'Married'), ('Divorced', 'Divorced'), ('Separated', 'Separated'), ('Never Married', 'Never Married'), ('Widowed', 'Widowed')], max_length=20, null=True)),
                ('living_situation', models.CharField(blank=True, choices=[('Parent1', 'Parent1'), ('Parent2', 'Parent2')], max_length=20, null=True)),
                ('children', models.BooleanField()),
                ('number_of_children', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Family',
            },
        ),
        migrations.CreateModel(
            name='Sibling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('relationship', models.CharField(blank=True, choices=[('Brother', 'Brother'), ('Sister', 'Sister')], max_length=50, null=True)),
                ('education_level', models.CharField(blank=True, max_length=100, null=True)),
                ('related_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_profile.family')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(blank=True, max_length=200, null=True)),
                ('date_started', models.DateField()),
                ('date_finished', models.DateField()),
                ('description', models.TextField(blank=True, max_length=250, null=True)),
                ('related_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_profile.education')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('nickname', models.CharField(blank=True, max_length=100, null=True)),
                ('other_name', models.CharField(blank=True, max_length=100, null=True)),
                ('sex', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20, null=True)),
                ('other_gender', models.CharField(blank=True, max_length=200, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Personal Information',
            },
        ),
        migrations.CreateModel(
            name='PersonalEssay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent', models.BooleanField(default=False)),
                ('essay', models.TextField(max_length=800)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Personal Essay',
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_type', models.CharField(blank=True, choices=[('Mother', 'Mother'), ('Father', 'Father'), ('Limited information', 'I have limited information about this parent')], max_length=100, null=True)),
                ('parent_status', models.BooleanField(verbose_name='Is parent living?')),
                ('parent_prefix', models.CharField(blank=True, choices=[('Dr.', 'Dr'), ('Ms.', 'Ms.'), ('Mr.', 'Mr.'), ('Mrs.', 'Mrs.')], max_length=10, null=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('birth_country', models.CharField(blank=True, max_length=50, null=True)),
                ('preferred_email', models.EmailField(blank=True, max_length=40, null=True)),
                ('preferred_phone', models.CharField(choices=[('Mobile', 'Mobile'), ('Home', 'Home'), ('Work', 'Work'), ('Other', 'Other')], max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('parent_address', models.CharField(blank=True, max_length=50, null=True)),
                ('occupation', models.CharField(blank=True, max_length=50)),
                ('education_level', models.CharField(blank=True, max_length=50, null=True)),
                ('related_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_profile.family')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('English', 'English'), ('Zulu', 'Zulu')], max_length=20, null=True)),
                ('language_proficiency', models.CharField(blank=True, choices=[('First language', 'First language'), ('Speak', 'Speak'), ('Read', 'Read'), ('Write', 'Write'), ('Spoken at home', 'Spoken at home')], max_length=50, null=True)),
                ('related_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_profile.demographic')),
            ],
        ),
        migrations.CreateModel(
            name='FuturePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_interest', models.CharField(blank=True, max_length=50, null=True)),
                ('highest_degree', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, max_length=350, null=True)),
                ('related_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_profile.education')),
            ],
        ),
        migrations.CreateModel(
            name='DisciplinaryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplinary', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True)),
                ('related_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_profile.personalessay')),
            ],
        ),
        migrations.CreateModel(
            name='ContactDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_option', models.CharField(blank=True, choices=[('Home', 'Home'), ('Mobile', 'Mobile')], max_length=20, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('related_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_profile.personalinformation')),
            ],
        ),
        migrations.CreateModel(
            name='Citizenship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('related_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_profile.demographic')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(blank=True, max_length=30, null=True)),
                ('related_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_profile.personalinformation')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('any_disruptions', models.BooleanField()),
                ('disruption', models.TextField(blank=True, max_length=650, null=True)),
                ('any_curcumstance', models.BooleanField(default=False)),
                ('circumstance', models.TextField(blank=True, max_length=650, null=True)),
                ('related_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_profile.personalessay')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_interest', models.BooleanField(blank=True, default=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(blank=True, choices=[('Art', 'Art'), ('Academic', 'Academic')], max_length=200, null=True)),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
                ('organization', models.CharField(blank=True, max_length=150, null=True, verbose_name='Oraganization Name')),
                ('accomplishment', models.CharField(blank=True, max_length=200, null=True)),
                ('intension', models.BooleanField()),
                ('hours_per_week', models.CharField(blank=True, max_length=200, null=True)),
                ('weeks_per_year', models.CharField(blank=True, max_length=200, null=True)),
                ('participation_time', models.CharField(blank=True, choices=[('During school year', 'During school year'), ('During school break', 'During school break'), ('All year', 'All year')], max_length=50, null=True)),
                ('related_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_profile.activitycheck')),
            ],
        ),
    ]
