# Generated by Django 3.2.4 on 2021-06-10 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Address2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Citizenship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_option', models.CharField(blank=True, choices=[('Home', 'Home'), ('Mobile', 'Mobile')], max_length=20, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Demographic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('religion', models.CharField(blank=True, choices=[('Christian', 'Christian'), ('Hindu', 'Hindu'), ('Muslim', 'Muslim')], max_length=30, null=True)),
                ('race', models.CharField(blank=True, choices=[('Black', 'Black'), ('White', 'White'), ('Asian', 'Asian')], max_length=30, null=True)),
                ('consent', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='First_Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_type', models.CharField(blank=True, choices=[('Mother', 'Mother'), ('Father', 'Father'), ('Limited information', 'I have limited information about this parent')], max_length=100, null=True)),
                ('parent_status', models.BooleanField(verbose_name='Is parent living?')),
                ('parent_prefix', models.CharField(blank=True, choices=[('Dr.', 'Dr'), ('Ms.', 'Ms.'), ('Mr.', 'Mr.'), ('Mrs.', 'Mrs.')], max_length=10, null=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('birth_country', models.CharField(blank=True, max_length=50, null=True)),
                ('preferred_email', models.EmailField(blank=True, max_length=40, null=True)),
                ('preferred_phone', models.CharField(choices=[('Mobile', 'Mobile'), ('Home', 'Home'), ('Work', 'Work'), ('Other', 'Other')], max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('parent_address', models.CharField(blank=True, max_length=50, null=True)),
                ('occupation', models.CharField(blank=True, max_length=50)),
                ('education_level', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'First Parent',
            },
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_status', models.CharField(blank=True, choices=[('Married', 'Married'), ('Divorced', 'Divorced'), ('Separated', 'Separated'), ('Never Married', 'Never Married'), ('Widowed', 'Widowed')], max_length=20, null=True)),
                ('living_situation', models.CharField(blank=True, choices=[('Parent1', 'Parent1'), ('Parent2', 'Parent2')], max_length=20, null=True)),
                ('children', models.BooleanField()),
                ('number_of_children', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_languages', models.IntegerField(blank=True, default=1, null=True)),
                ('language', models.CharField(blank=True, choices=[('English', 'English'), ('Zulu', 'Zulu')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('nickname', models.CharField(blank=True, max_length=100, null=True)),
                ('other_name', models.CharField(blank=True, max_length=100, null=True)),
                ('sex', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20, null=True)),
                ('other_gender', models.CharField(blank=True, max_length=200, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Second_Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_type', models.CharField(blank=True, choices=[('Mother', 'Mother'), ('Father', 'Father'), ('Limited information', 'I have limited information about this parent')], max_length=100, null=True)),
                ('parent_status', models.BooleanField(verbose_name='Is parent living?')),
                ('parent_prefix', models.CharField(blank=True, choices=[('Dr.', 'Dr'), ('Ms.', 'Ms.'), ('Mr.', 'Mr.'), ('Mrs.', 'Mrs.')], max_length=10, null=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('birth_country', models.CharField(blank=True, max_length=50, null=True)),
                ('preferred_email', models.EmailField(blank=True, max_length=40, null=True)),
                ('preferred_phone', models.CharField(choices=[('Mobile', 'Mobile'), ('Home', 'Home'), ('Work', 'Work'), ('Other', 'Other')], max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('parent_address', models.CharField(blank=True, max_length=50, null=True)),
                ('occupation', models.CharField(blank=True, max_length=50)),
                ('education_level', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Second Parent',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_profile.address')),
                ('citizenship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_profile.citizenship')),
                ('contact_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_profile.contactdetail')),
                ('demographics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_profile.demographic')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_profile.language')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_profile.personalinformation')),
            ],
            options={
                'verbose_name': 'Profile (Parent)',
            },
        ),
    ]
