# Generated by Django 3.2.4 on 2021-06-13 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name_plural': 'Education'},
        ),
        migrations.AlterModelOptions(
            name='family',
            options={'verbose_name_plural': 'Family'},
        ),
        migrations.AlterModelOptions(
            name='personalinformation',
            options={'verbose_name_plural': 'Personal Information'},
        ),
    ]
