# Generated by Django 3.2.4 on 2021-06-10 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address2',
            old_name='address',
            new_name='address2',
        ),
        migrations.RenameField(
            model_name='address2',
            old_name='city',
            new_name='city2',
        ),
        migrations.RenameField(
            model_name='address2',
            old_name='country',
            new_name='country2',
        ),
        migrations.RenameField(
            model_name='address2',
            old_name='postal_code',
            new_name='postal_code2',
        ),
        migrations.AddField(
            model_name='address',
            name='address2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_profile.address2'),
        ),
    ]
