# Generated by Django 3.2.4 on 2021-06-10 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0002_auto_20210610_0625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address2',
        ),
        migrations.AddField(
            model_name='address2',
            name='related_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_profile.address'),
        ),
    ]
