# Generated by Django 3.2.4 on 2021-06-10 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0003_auto_20210610_0630'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address2',
            options={'verbose_name_plural': 'Address line 2'},
        ),
    ]
