# Generated by Django 3.2.4 on 2021-06-10 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0004_alter_address2_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address2',
            old_name='address2',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='address2',
            old_name='city2',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='address2',
            old_name='country2',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='address2',
            old_name='postal_code2',
            new_name='postal_code',
        ),
    ]
