# Generated by Django 3.2.4 on 2021-06-10 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0005_auto_20210610_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(blank=True, max_length=200, null=True)),
                ('date_of_entry', models.DateField()),
                ('school_type', models.BooleanField()),
                ('graduation_status', models.BooleanField()),
                ('graduation_date', models.DateField(blank=True, null=True)),
                ('progression_status', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OtherSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(blank=True, max_length=200, null=True)),
                ('date_started', models.DateField()),
                ('date_finished', models.DateField()),
                ('related_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_profile.school')),
            ],
        ),
    ]
