# Generated by Django 3.2.4 on 2021-06-10 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0006_otherschool_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
