# Generated by Django 3.2.4 on 2021-06-10 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0007_schooldescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooldescription',
            name='related_school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_profile.school'),
        ),
    ]
