# Generated by Django 3.2.4 on 2021-06-10 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0008_schooldescription_related_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='first_parent',
            name='related_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_profile.first_parent'),
        ),
    ]
