# Generated by Django 3.2.4 on 2021-06-10 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0009_first_parent_related_parent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='First_Parent',
            new_name='FirstParent',
        ),
        migrations.RenameModel(
            old_name='Second_Parent',
            new_name='SecondParent',
        ),
    ]
