# Generated by Django 3.2.4 on 2021-06-10 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0010_auto_20210610_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firstparent',
            name='related_parent',
        ),
        migrations.AddField(
            model_name='secondparent',
            name='related_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_profile.firstparent'),
        ),
    ]
