# Generated by Django 3.2.4 on 2021-06-10 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0011_auto_20210610_2350'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FirstParent',
            new_name='Parent',
        ),
        migrations.AlterModelOptions(
            name='parent',
            options={},
        ),
    ]
