# Generated by Django 3.2.4 on 2021-06-11 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0012_auto_20210610_2354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Siblings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('relationship', models.CharField(blank=True, choices=[('Brother', 'Brother'), ('Sister', 'Sister')], max_length=50, null=True)),
                ('education_level', models.CharField(blank=True, max_length=100, null=True)),
                ('related_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_profile.parent')),
            ],
        ),
    ]
