# Generated by Django 3.2.4 on 2021-06-11 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0015_remove_language_number_of_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='related_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_profile.demographic'),
        ),
    ]
