# Generated by Django 3.2.4 on 2021-06-11 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0016_language_related_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='language_proficiency',
            field=models.CharField(blank=True, choices=[('First language', 'First language'), ('Speak', 'Speak'), ('Read', 'Read'), ('Write', 'Write'), ('Spoken at home', 'Spoken at home')], max_length=50, null=True),
        ),
    ]
