# Generated by Django 3.2.4 on 2021-06-11 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0018_contactdetail_related_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizenship',
            name='related_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_profile.demographic'),
        ),
    ]
