# Generated by Django 3.2.4 on 2021-06-11 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0019_citizenship_related_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuturePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_interest', models.CharField(blank=True, max_length=50, null=True)),
                ('highest_degree', models.CharField(blank=True, max_length=50, null=True)),
                ('notoes', models.TextField(blank=True, max_length=350, null=True)),
            ],
        ),
    ]
