# Generated by Django 3.2.4 on 2021-06-11 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0020_futureplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_interest', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(blank=True, choices=[('Art', 'Art'), ('Academic', 'Academic')], max_length=200, null=True)),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
                ('organization', models.CharField(blank=True, max_length=150, null=True, verbose_name='Oraganization Name')),
                ('accomplishment', models.CharField(blank=True, max_length=200, null=True)),
                ('intension', models.BooleanField()),
                ('hours_per_week', models.CharField(blank=True, max_length=200, null=True)),
                ('weeks_per_year', models.CharField(blank=True, max_length=200, null=True)),
                ('participation_time', models.CharField(blank=True, choices=[('During school year', 'During school year'), ('During school break', 'During school break'), ('All year', 'All year')], max_length=50, null=True)),
                ('related_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_profile.activitycheck')),
            ],
        ),
    ]
