# Generated by Django 3.2.4 on 2021-06-11 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0021_activity_activitycheck'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalEssay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent', models.BooleanField(default=False)),
                ('essay', models.TextField(max_length=800)),
            ],
            options={
                'verbose_name': 'Personal Essay (Parent)',
            },
        ),
        migrations.CreateModel(
            name='DisciplinaryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplinary', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True)),
                ('related_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_profile.personalessay')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('any_disruptions', models.BooleanField()),
                ('disruption', models.TextField(blank=True, max_length=650, null=True)),
                ('any_curcumstances', models.BooleanField()),
                ('circumstance', models.TextField(blank=True, max_length=650, null=True)),
                ('related_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_profile.personalessay')),
            ],
        ),
    ]
