# Generated by Django 3.2.4 on 2021-06-11 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0022_additionalinformation_disciplinaryhistory_personalessay'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalessay',
            options={'verbose_name_plural': 'Personal Essay'},
        ),
    ]
